### PR TITLE
Rework everything

### PR DESCRIPTION
**Pull request by Kenny2github**
### Changes
* Packagify everything
+ Pass Pylint
* Optimized in a few places

### CODE REVIEW

**Comment by apple502j** [comment]
I'll check the code.

**Review by apple502j — COMMENTED** [review]
setup.py 16:
This program won't work in Python 2.7
(Don't worry, it's too small to reject)

**Review by apple502j — CHANGES_REQUESTED** [review]
I can't run your script....
```
  File "C:\Python\lib\site-packages\mwsyntaxchecker-1.0.0-py3.6.egg\MWSyntaxChecker\__init__.py", line 4, in <module>
    from MWSyntaxChecker import Checks
ImportError: cannot import name 'Checks'
```

**Comment by apple502j** [comment]
Uninstall Error
```
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\pip3.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\pip\_internal\__init__.py", line 246, in mai
n
    return command.main(cmd_args)
  File "c:\python\lib\site-packages\pip\_internal\basecommand.py", line 264, in
main
    timeout=min(5, options.timeout)) as session:
  File "c:\python\lib\site-packages\pip\_internal\basecommand.py", line 81, in _
build_session
    insecure_hosts=options.trusted_hosts,
  File "c:\python\lib\site-packages\pip\_internal\download.py", line 338, in __i
nit__
    self.headers["User-Agent"] = user_agent()
  File "c:\python\lib\site-packages\pip\_internal\download.py", line 127, in use
r_agent
    setuptools_version = get_installed_version("setuptools")
  File "c:\python\lib\site-packages\pip\_internal\utils\misc.py", line 829, in g
et_installed_version
    working_set = pkg_resources.WorkingSet()
  File "c:\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 558, in __init__
    self.add_entry(entry)
  File "c:\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 614, in add_entry
    for dist in find_distributions(entry, True):
  File "c:\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 1882, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "c:\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 1399, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "c:\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 1756, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "c:\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 1633, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "c:\python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 1590, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。: 'c:\\pytho
n\\lib\\site-packages\\mwsyntaxchecker-1.0.0-py3.6.egg'
```

**Review by apple502j — APPROVED** [review]
Good!
